### ISSUE TITLE
use_sf() cannot find function

### ISSUE THREAD

**Issue by gypsy-moth** [rsbivand/rgrass7#12]
Hi, I am trying to get rgrass7 running.
I am following along the tutorial of _Geocomputation with R_, chapter _9.4 GRASS through rgrass7_.
https://geocompr.robinlovelace.net/gis.html#rgrass

Initiating a grass session seems to work fine so far.
But when I try to run **use_sf()**, I get a message stating this function cannot be found.

I'm running Microsoft R Open 3.5.3 on Windows 10.

I am grateful for any help.

**Comment by rsbivand** [comment]
Do search issues for your problem first, and review posts  on https://lists.osgeo.org/mailman/listinfo/grass-stats google-search lists:grass-stats use_sf. Put `use_sp()` at the top of your script if only using raster objects; **sf** can be used for vector objects by `use_sf()`.

**Comment by Crnagora28** [comment]
Manually, this is the function. For today's version of rgrass you also have to download terra for certain functions to work.   
  use_sf <- function() {
    options(rgrass.use_sf = TRUE)
    invisible(TRUE)
  }

**Comment by veroandreo** [comment]
The function `use_sf()` is no longer used in _rgrass_. It was a temporary solution in the transition to deprecate _rgdal_ and _sp_. The package _terra_ is now used to read vector and raster data from GRASS into R, with `read_VECT()` and `read_RAST()` respectively. Once there, you can convert the resulting objects into other formats.

**Comment by rsbivand** [comment]
@Crnagora28 @veroandreo With modern `rgrass`, you can refer to https://osgeo.github.io/rgrass/articles/coerce.html for coercion from `SpatRaster` or `SpatVector` to other object representations.
