### ISSUE TITLE
Error in readVECT:  "either sp or sf must be chosen"

### ISSUE THREAD

**Issue by pat-s** [rsbivand/rgrass7#9]
```r
rgrass7::initGRASS("/opt/grass", override = TRUE)
readVECT("shortest_route", plugin = FALSE)
Error in readVECT("shortest_route", plugin = FALSE) : 
  either sp or sf must be chosen
```

I found out that I need to call `rgrass7::use_sf()` or `rgrass7::use_sp()` upfront.
However, I just found this by browsing the functions in the package (and the package source code) and by guessing that this one might help.
Maybe the error message could be improved at this point to point to these functions.

**Comment by rsbivand** [comment]
Is https://github.com/rsbivand/rgrass7/commit/bd8fe8273afc266c600b6557b4bacf6ddd61348c OK?

**Comment by pat-s** [comment]
Looks good!
